CREATE TABLE IF NOT EXISTS authors
(
    id    BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS posts
(
    id        BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title     VARCHAR(255) NOT NULL,
    content   TEXT         NOT NULL,
    author_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (author_id) REFERENCES authors (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    content   TEXT NOT NULL,
    author_id BIGINT UNSIGNED NOT NULL,
    post_id   BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (author_id) REFERENCES authors (id),
    FOREIGN KEY (post_id) REFERENCES posts (id)
);